import { jsPDF } from 'jspdf';

export const PDF_PAGE = {
  width: 210,
  height: 297,
  margin: 16,
} as const;

export const PDF_COLORS = {
  gold: [180, 145, 90] as [number, number, number],
  goldDark: [160, 120, 60] as [number, number, number],
  ink: [20, 20, 20] as [number, number, number],
  body: [80, 80, 76] as [number, number, number],
  muted: [120, 120, 116] as [number, number, number],
  faint: [140, 140, 136] as [number, number, number],
  line: [200, 200, 196] as [number, number, number],
  panel: [248, 248, 244] as [number, number, number],
  panelBorder: [220, 210, 190] as [number, number, number],
  barTrack: [220, 220, 218] as [number, number, number],
  success: [40, 100, 40] as [number, number, number],
  risk: [160, 60, 60] as [number, number, number],
};

export const PDF_DISCLAIMER =
  'This report is generated by AI analysis of uploaded digitals and is intended as a decision-support tool only. Context alignment scores do not constitute professional casting advice and should be used alongside agent judgment. CastView does not guarantee casting outcomes.';

/** jsPDF built-in Helvetica only supports Latin-1 — strip/replace Unicode. */
export function pdfSafeText(text: string): string {
  return text
    .replace(/\u2192/g, '->')
    .replace(/\u00b7/g, ' | ')
    .replace(/\u2013|\u2014/g, '-')
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201c\u201d]/g, '"')
    .replace(/\u2026/g, '...')
    .replace(/[^\t\n\r\x20-\x7E\xA0-\xFF]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

export type CastviewPdf = {
  doc: jsPDF;
  pageW: number;
  pageH: number;
  margin: number;
  fullW: number;
  colW: number;
  y: number;
};

export function createCastviewPdf(): CastviewPdf {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const { width: pageW, height: pageH, margin } = PDF_PAGE;
  const fullW = pageW - margin * 2;
  const colW = (fullW - 8) / 2;

  return { doc, pageW, pageH, margin, fullW, colW, y: margin };
}

export function pdfCheckBreak(pdf: CastviewPdf, need: number): void {
  if (pdf.y + need > pdf.pageH - pdf.margin) {
    pdf.doc.addPage();
    pdfDrawTopAccent(pdf);
    pdf.y = 10;
  }
}

export function pdfDrawTopAccent(pdf: CastviewPdf): void {
  pdf.doc.setFillColor(...PDF_COLORS.gold);
  pdf.doc.rect(0, 0, pdf.pageW, 3, 'F');
}

export function pdfDrawBottomAccent(pdf: CastviewPdf): void {
  pdf.doc.setFillColor(...PDF_COLORS.gold);
  pdf.doc.rect(0, pdf.pageH - 2, pdf.pageW, 2, 'F');
}

export function pdfLabel(
  pdf: CastviewPdf,
  text: string,
  x: number,
  y: number,
  color: [number, number, number] = PDF_COLORS.muted,
): void {
  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(7);
  pdf.doc.setTextColor(...color);
  pdf.doc.text(pdfSafeText(text).toUpperCase(), x, y);
}

export function pdfBody(
  pdf: CastviewPdf,
  text: string,
  x: number,
  y: number,
  maxW: number,
  color: [number, number, number] = PDF_COLORS.body,
): number {
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(8);
  pdf.doc.setTextColor(...color);
  const lines = pdf.doc.splitTextToSize(pdfSafeText(text), maxW);
  pdf.doc.text(lines, x, y);
  return lines.length * 4.2;
}

export function pdfBullet(
  pdf: CastviewPdf,
  text: string,
  x: number,
  y: number,
  maxW: number,
): number {
  return pdfBody(pdf, `- ${text}`, x, y, maxW);
}

export function pdfHr(pdf: CastviewPdf): void {
  pdf.doc.setDrawColor(...PDF_COLORS.line);
  pdf.doc.setLineWidth(0.3);
  pdf.doc.line(pdf.margin, pdf.y, pdf.pageW - pdf.margin, pdf.y);
  pdf.y += 8;
}

export function pdfDrawHeader(pdf: CastviewPdf, showContact = true): void {
  pdfDrawTopAccent(pdf);
  pdf.y = 10;

  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(9);
  pdf.doc.setTextColor(...PDF_COLORS.gold);
  pdf.doc.text('CASTVIEW', pdf.margin, pdf.y);

  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(7);
  pdf.doc.setTextColor(...PDF_COLORS.faint);
  const contact = showContact
    ? 'castview.org | hello@castview.org'
    : 'castview.org';
  pdf.doc.text(contact, pdf.pageW - pdf.margin, pdf.y, { align: 'right' });
  pdf.y += 8;

  pdfHr(pdf);
}

export function pdfDrawProspectSection(
  pdf: CastviewPdf,
  prospectName: string,
  options: { showGeneratedDate?: boolean } = {},
): void {
  const { showGeneratedDate = true } = options;

  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(7);
  pdf.doc.setTextColor(...PDF_COLORS.faint);
  pdf.doc.text('PROSPECT', pdf.margin, pdf.y);

  if (showGeneratedDate) {
    pdf.doc.setFont('helvetica', 'normal');
    pdf.doc.setFontSize(7);
    pdf.doc.text(
      `Generated: ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
      })}`,
      pdf.pageW - pdf.margin,
      pdf.y,
      { align: 'right' },
    );
  }
  pdf.y += 5;

  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(22);
  pdf.doc.setTextColor(...PDF_COLORS.ink);
  pdf.doc.text(pdfSafeText(prospectName), pdf.margin, pdf.y);
  pdf.y += 10;
}

export function pdfDrawMetaRow(pdf: CastviewPdf, items: string[]): void {
  const cleaned = items.map(pdfSafeText).filter(Boolean);
  if (cleaned.length === 0) return;

  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(7.5);
  pdf.doc.setTextColor(...PDF_COLORS.muted);
  const metaLines = pdf.doc.splitTextToSize(cleaned.join(' | '), pdf.fullW);
  pdf.doc.text(metaLines, pdf.margin, pdf.y);
  pdf.y += metaLines.length * 4.5 + 4;
}

export function pdfDrawSectionTitle(pdf: CastviewPdf, title: string): void {
  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(20);
  pdf.doc.setTextColor(...PDF_COLORS.ink);
  pdf.doc.text(pdfSafeText(title), pdf.margin, pdf.y);
  pdf.y += 6;
}

export function pdfDrawSubtitle(pdf: CastviewPdf, text: string): void {
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(8);
  pdf.doc.setTextColor(...PDF_COLORS.body);
  const lines = pdf.doc.splitTextToSize(pdfSafeText(text), pdf.fullW);
  pdf.doc.text(lines, pdf.margin, pdf.y);
  pdf.y += lines.length * 4.2 + 4;
}

export function pdfDrawContextBar(
  pdf: CastviewPdf,
  contextName: string,
  rightLabel: string,
): void {
  pdf.doc.setFillColor(...PDF_COLORS.panel);
  pdf.doc.roundedRect(pdf.margin, pdf.y, pdf.fullW, 10, 1, 1, 'F');
  pdf.doc.setDrawColor(...PDF_COLORS.panelBorder);
  pdf.doc.roundedRect(pdf.margin, pdf.y, pdf.fullW, 10, 1, 1, 'S');

  pdf.doc.setFont('helvetica', 'bold');
  pdf.doc.setFontSize(8);
  pdf.doc.setTextColor(...PDF_COLORS.goldDark);
  pdf.doc.text(pdfSafeText(contextName).toUpperCase(), pdf.margin + 5, pdf.y + 6);

  pdf.doc.setTextColor(...PDF_COLORS.ink);
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.text(pdfSafeText(rightLabel), pdf.pageW - pdf.margin - 5, pdf.y + 6, {
    align: 'right',
  });
  pdf.y += 12;
}

export function pdfDrawScoreBar(pdf: CastviewPdf, score: number): void {
  const clamped = Math.max(0, Math.min(100, score));
  pdf.doc.setFillColor(...PDF_COLORS.barTrack);
  pdf.doc.rect(pdf.margin, pdf.y, pdf.fullW, 2, 'F');
  pdf.doc.setFillColor(...PDF_COLORS.gold);
  pdf.doc.rect(pdf.margin, pdf.y, pdf.fullW * (clamped / 100), 2, 'F');
  pdf.y += 6;
}

export function pdfDrawScoreTransition(
  pdf: CastviewPdf,
  oldScore: number,
  oldLabel: string,
  newScore: number,
  newLabel: string,
): void {
  const text = `${oldScore} (${oldLabel}) -> ${newScore} (${newLabel})`;
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(8);
  pdf.doc.setTextColor(...PDF_COLORS.ink);
  pdf.doc.text(pdfSafeText(text), pdf.pageW - pdf.margin - 5, pdf.y + 6, {
    align: 'right',
  });
}

export function pdfDrawAgentNotesBox(pdf: CastviewPdf, notes: string): void {
  const notesText = pdfSafeText(notes.trim()) || 'No agent notes added.';
  const notesLines = pdf.doc.splitTextToSize(notesText, pdf.fullW - 12);
  const notesBoxH = notesLines.length * 4.5 + 14;

  pdf.doc.setFillColor(...PDF_COLORS.panel);
  pdf.doc.roundedRect(pdf.margin, pdf.y, pdf.fullW, notesBoxH, 2, 2, 'F');
  pdf.doc.setDrawColor(...PDF_COLORS.panelBorder);
  pdf.doc.roundedRect(pdf.margin, pdf.y, pdf.fullW, notesBoxH, 2, 2, 'S');
  pdf.y += 6;
  pdfLabel(pdf, 'Agent Notes', pdf.margin + 6, pdf.y, PDF_COLORS.goldDark);
  pdf.y += 5;
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(8.5);
  pdf.doc.setTextColor(...PDF_COLORS.body);
  pdf.doc.text(notesLines, pdf.margin + 6, pdf.y);
  pdf.y += notesLines.length * 4.5 + 8;
}

export function pdfDrawDisclaimer(pdf: CastviewPdf): void {
  pdfCheckBreak(pdf, 24);
  pdf.doc.setDrawColor(...PDF_COLORS.line);
  pdf.doc.line(pdf.margin, pdf.y, pdf.pageW - pdf.margin, pdf.y);
  pdf.y += 5;

  const dlLines = pdf.doc.splitTextToSize(PDF_DISCLAIMER, pdf.fullW);
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(7);
  pdf.doc.setTextColor(...PDF_COLORS.faint);
  pdf.doc.text(dlLines, pdf.margin, pdf.y);
  pdf.y += dlLines.length * 3.8 + 5;
}

export function pdfDrawPreparedBy(pdf: CastviewPdf): void {
  pdf.doc.setFont('helvetica', 'normal');
  pdf.doc.setFontSize(7);
  pdf.doc.setTextColor(...PDF_COLORS.goldDark);
  pdf.doc.text('Prepared by CastView | castview.org', pdf.pageW / 2, pdf.y, {
    align: 'center',
  });
}

export function pdfDrawPageNumbers(pdf: CastviewPdf): void {
  const totalPages = pdf.doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.doc.setPage(i);
    pdf.doc.setFont('helvetica', 'normal');
    pdf.doc.setFontSize(7);
    pdf.doc.setTextColor(...PDF_COLORS.faint);
    pdf.doc.text(`${i} / ${totalPages}`, pdf.pageW / 2, pdf.pageH - 6, {
      align: 'center',
    });
  }
}

export function pdfSave(pdf: CastviewPdf, filename: string): void {
  pdfDrawBottomAccent(pdf);
  pdf.doc.save(pdfSafeText(filename).replace(/\s+/g, '-'));
}
